# Generated by Django 6.0.8 on 2026-09-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
