# Generated by Django 6.0.8 on 2026-09-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_types', '0001_initial'),
        ('requests', '0002_request_rejection_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='request_types.requesttype'),
        ),
    ]
