# Generated by Django 6.0.8 on 2026-09-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_verifier_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
