# Generated by Django 6.0.8 on 2026-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_request_current_verifier_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_approver_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
