# Generated by Django 6.0.8 on 2026-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_requestapproveraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='request_attachments/'),
        ),
    ]
