# Generated by Django 6.0.8 on 2026-09-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_request_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='action_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
