# Generated by Django 6.0.8 on 2026-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_request_action_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deadline_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
