# Generated by Django 6.0.8 on 2026-09-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_requestassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DECISION_REQUIRED', 'Decision Required')], default='PENDING', max_length=20),
        ),
    ]
