# Generated by Django 6.0.8 on 2026-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='verification_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
