# Generated by Django 6.0.8 on 2026-09-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=20)),
                ('approver_mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='request_types.requesttype')),
            ],
        ),
    ]
