# Generated by Django 6.0.8 on 2026-09-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('requests', '0014_alter_request_status'),
        ('workflow', '0003_workflowassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='requests.request'),
        ),
    ]
